### ISSUE TITLE
Crash on Windows with OBS Studio installed but no USB cam

### ISSUE THREAD

**Issue by dani-carbonell** [grillbaer/spectracle#13]
Hi Holger, 
This project looks great but I after installing the Maven Java Build #23 in a Windows 10 machine, I double click on the Spectracle icon and nothing happens. I have tried different compatibility modes. I dont have any camera pluged in my computer.

What could I try?

Thank you

**Comment by grillbaer** [comment]
Hi Dani,
I just added some basic log output for better diagnosis. Log files will now be written to `%TMP%\spectracle`.
Could you please uninstall the previous build, retry with [#24](https://github.com/grillbaer/spectracle/actions/runs/1407651271) and attach the latest log file?

**Comment by dani-carbonell** [comment]
Thanks for the fast response. This is my logfile.
It seems like its recognizing a camera that is the same resolution than my screen.
If I open the "Camera App" in Windows 10 it cannot find any camera though. 

[spectracle.log](https://github.com/grillbaer/spectracle/files/7452956/spectracle.log)

**Comment by dani-carbonell** [comment]
Good news.
I just connected a USB microscope camera I had lying arround and now the app opens succesfully.
When I click in the Camera reload button the app closes again even with the camera plugged

**Comment by grillbaer** [comment]
Looks like a hard crash at grabbing the first frame from the initially available "camera" 0. Opening and initializing the cam still works, but then the program seems to be gone suddenly. This probably happens somewhere within the used OpenCV video library. Will be difficult to diagnose.

Is there any camera shown in your Windows Device Manager?
I'd like to know what kind of video capture device it is. Maybe some virtual cam.

**Comment by dani-carbonell** [comment]
I also suspected that there must be a virtual camera causing this error but when I unplug all my cameras there is no camera listed in the Device Manager.
I still decided to uninstall the OBS Studio and try again with no cameras and....... It worked. This sofware was causing the issue.
I would add a small text in the documentation with a warning about trying to run the software without a real camera connected.

Thanks for the support and for the great software.

**Comment by grillbaer** [comment]
Thank you for your investigations! When I find some time for it, I'd like to look for an alternative to OpenCV that allows to better identify/filter capture devices and that has a more predictable behavior (issue #6). This crash is another argument for that step.

I'll close this issue for now and add a hint to the readme, as suggested.
